//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingVersionGetItDone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        public int BarID { get; set; }
        public string BarName { get; set; }
        public string BarStreet { get; set; }
        public string BarCity { get; set; }
        public string BarState { get; set; }
        public string BarPhone { get; set; }
        public string BarZip { get; set; }
    }
}
