//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingVersionGetItDone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public int StadiumID { get; set; }
        public Nullable<System.TimeSpan> GameTime { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
    }
}
