//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingVersionGetItDone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public int GroupOwnerID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int GameID { get; set; }
        public string EventType { get; set; }
        public string EventLocationName { get; set; }
        public bool Confirmed { get; set; }
    }
}
