//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingVersionGetItDone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadium
    {
        public int StadiumID { get; set; }
        public string StadiumName { get; set; }
        public string StadiumAddress { get; set; }
        public string StadiumCity { get; set; }
        public string StadiumState { get; set; }
        public int StadiumZip { get; set; }
        public int HomeTeamID { get; set; }
    }
}
